spring:
  application:
    name: c-gateway-service
  cloud:
    nacos:
      config:
        server-addr: 10.12.47.202:8848
        file-extension: yaml
      server-addr: 10.12.47.202:8848
  config:
    import:
      - optional:nacos:c-gateway-service-dev.yaml

management:
  endpoints:
    web:
      exposure:
        include=*:

logging:
  level:
    org.springframework.cloud.gateway: trace