server:
  port: 7003

spring:
  application:
    name: c-product-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 127.0.0.1
    port: 6379
  data:
    mongodb:
      uri: mongodb://localhost:27017/cartoon
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cartoon?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  #文件上传大小限制
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: INFO

