server:
  port: 7002

spring:
  application:
    name: c-file-service
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cartoon?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  minio:
    bucket: cartoon
    access-key: n97ICA2paP4joim83VtV
    secret-key: MAWJX1FO3GACjdmfILyib1hG8ezr5hiQOResDekp
    url: http://127.0.0.1:9000/

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    ROOT: info
    com.minio: debug
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{50} - %msg%n'

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tHw8XzvHiyyDB4uT8sM
    access-key-secret: Dz5hNYeF6wJzXtVoJ8kzCit8Qyy8gT
    bucket-name: tute-chat




